### ISSUE TITLE
Read receipts support

### ISSUE THREAD

**Issue by mitchcapper** [signal-csharp/libsignal-service-dotnet#21]
So I started noticing messages that were ```isSignalMessage: True isReceipt: False```
that were essentially unrecognized following the logic of  https://github.com/signal-csharp/Signal-Windows/blob/master/Signal-Windows.Lib/IncomingMessages.cs#L96-L165

The decoded message is empty.   I am quite confident the messages are read receipts from watching when they are generated.  While the logic followed is Signal-Windows logic I don't seem to find the content on SignalServiceContent that one could use for read receipts.

I tried looking at the server specs and protocol, I am not seeing what is missed.  I saw sync messages that seemed to deal with it but we don't seem to be getting a normal sync message type.
As the protocol buffer returns something empty I am not sure if it is an envelope field or otherwise that is being missed.

**Comment by Trolldemorted** [comment]
Signal-Windows does not yet support it (but most likely will soon), but I believe it should work.

Read messages do not contain the sent message, but you can use their timestamps to identify the message: https://github.com/signalapp/Signal-Android/blob/43622e603dc880262e72ebd205fd3309ea15560a/src/org/thoughtcrime/securesms/jobs/PushDecryptJob.java#L499

**Comment by mitchcapper** [comment]
It seems content.SynchronizeMessage.getRead() would be the check for if it is a read receipt however SynchronizeMessage is null on the messages infact the entire message from 11 bytes of encoded data when parsed through:
https://github.com/signal-csharp/libsignal-service-dotnet/blob/master/libsignal-service-dotnet/crypto/SignalServiceCipher.cs#L90
shows nothing.  There is 1 unknown field so I am not sure if that is related.
![no_fields](https://user-images.githubusercontent.com/1643324/39678979-c3684832-514b-11e8-8053-7d1b388c2f10.png)

**Comment by Trolldemorted** [comment]
content.SynchronizeMessage.getRead() is a list of readMessages:

```
public May<List<ReadMessage>> getRead();
```
![grafik](https://user-images.githubusercontent.com/10261186/39726164-786bbd6a-524e-11e8-98de-724e51aec14e.png)

**Comment by mitchcapper** [comment]
Hrm. On the decode however I am getting SynchronizeMessage is null per the above.    It is odd as normally decoding is fine.  Using the latest libsignal-protocol-dotnet.  I reverted to the official nuget to double check.  I tried read receipts from both the official android app and the official windows app to be safe.

**Comment by Trolldemorted** [comment]
That is odd. You placed a breakpoint [here](https://github.com/signal-csharp/Signal-Windows/blob/master/Signal-Windows.Lib/IncomingMessages.cs#L155), marked messages as read on Signal-Android, but the breakpoint does not fire?

Signal-Windows does not yet sending and receiving read messages, we are working on it right now. Nevertheless a breakpoint on the foreach loop should fire, and you should be able to inspect the list of ReadMessages with visual studio's debugger.

Just to make sure, we are talking about synced read messages, right? Messages sent from a sibling device indicating that you read an incoming messages, not read confirmations you send to your contacts.

**Comment by mitchcapper** [comment]
NO! Sorry for the confusion and thank you for the clarification.  I am talking about read confirmations from contacts on a message when they have read receipts enabled.
Technically I put my breakpoint far deeper into signal I placed it right after the ParseFrom command:
https://github.com/signal-csharp/libsignal-service-dotnet/blob/master/libsignal-service-dotnet/crypto/SignalServiceCipher.cs#L90

as I was not getting the data at a much higher level.  If after that decode however syncmessage is null nothing else can happen.

While I didn't try debugging in the Signal-Windows code essentially the message would end up in:
https://github.com/signal-csharp/Signal-Windows/blob/master/Signal-Windows.Lib/IncomingMessages.cs#L163
saying an unknown message.

**Comment by mitchcapper** [comment]
If the protocol buffer says there is an unknown field does that mean we should update the proto-buf definitions?

**Comment by Trolldemorted** [comment]
That explains the problem, then: receipt messages were added with libsignal-service 2.6.6 while this libsignal-service has not been updated beyond 2.5.15.

Parsing won't work because the protobuf fields were added in https://github.com/signalapp/libsignal-service-java/commit/59ff4348d5e6307d31f4133dfde9f84e195a3a9e.

I would have updated libsignal-service-dotnet earlier, but the next iteration depends on a change in libsignal-protocol, which depends on a major change in curve25519:

https://github.com/signalapp/curve25519-java/commit/b71b9f135d3941ca7e8eafd3807f68e688dd5891

I had already started porting it, but replicating C's pointer arithmetic in C# is cumbersome. Since you appear to know a lot more about dotnet packaging, can we compile the C code for windows on x86, x64 and ARM and call it from C#?

I dislike our own implementation because of the maintenence overhead and because the timing attack resistance could be gone due to optimizations of the .net native compiler.

**Comment by mitchcapper** [comment]
Perfect that all lines up.
So I am no expert to say the least.
With that said you can 100% compile C/C++ code for .NET use!  Sadly .net core/standard has no plans for this support so it is fairly useless for this (dotnet/coreclr#659).
Maintaining all of these things is certainly a PITA I am sure.  I don't know the signal protocol very well, but there a likely chance of using an external curve25519 library?

**Comment by Trolldemorted** [comment]
That depends a lot on who is the author, if microsoft were to release it I believe we would switch asap.

There is a [proposal](https://github.com/dotnet/corefx/issues/2106) to add curve25519 to dotnet standard, but who knows when and for which versions they will implement it.

Someone has tried to use [ECCurve](https://github.com/dotnet/corefx/issues/19168) for a custom curve25519 implementation, and I have asked to backport [ECCurve to netstandard1.4](https://github.com/dotnet/corefx/issues/29403). Not sure if any of that succeeds, though.

Since updates to curve25519-java happen very rarely, we could also try to adapt the patch. Maybe the original authors of curve25519-dotnet/pcl can give us a hint how they converted it, since we have no weird dependencies and I/O we might have some luck and they used an automatic converter and it just worked.

cc @smndtrl, @langboost, @golf1052

**Comment by golf1052** [comment]
When I did the updates [here](https://github.com/golf1052/curve25519-pcl/commits/master) they were all done manually, commit by commit.

Looking on the threads you've linked I noticed [this library](https://github.com/ektrah/nsec). I wonder if we could use this instead?

**Comment by Trolldemorted** [comment]
I have updated libsignal-protocol without migrating the changes to curve25519 yet, because the changes do to my best knowledge not change the behaviour of the package.

I will update libsignal-service-dotnet in the next days, but some commits are rather large, so it might take some time. Most stuff will be untested because Signal-Windows is not yet able to test it, but we should archieve read messages support soon.

**Comment by Trolldemorted** [comment]
Went smoother than expected, 2.6.6 is being pushed to nuget and myget!

Receiving read messages works fine:
![grafik](https://user-images.githubusercontent.com/10261186/39992773-1d0ce82e-5774-11e8-8c7f-de0195e40101.png)

but I cannot test whether sending works, as Signal-Windows doesn't support it yet. If it doesn't work, please let me know!

**Comment by mitchcapper** [comment]
confirmed this seems to be working well with the new library.

**Comment by Trolldemorted** [comment]
Splendid! 🎉
